import React,{useState} from 'react';
import {parseShowingReport,showingSummary} from '../showings.js';
const date=s=>new Date(s+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'});
const time=s=>{const [h,m]=s.split(':');return `${+h%12||12}:${m} ${+h>=12?'PM':'AM'}`;};
export function Showings({report,prices,day}){
 const s=showingSummary(report,prices,day);
 return <section className="section"><div className="section-title"><div><div className="eyebrow">SHOWING ACTIVITY</div><h2>Property Showings</h2></div>{report&&<span>Report through {date(report.through)}</span>}</div>{!report?<p className="showing-note">Showing activity will appear after an administrator imports a ShowingTime report.</p>:<><div className="showing-stats"><article><h3>Completed showings</h3><strong>{s.completed}</strong><p>Recorded as past showings in the report</p></article><article><h3>Since latest price adjustment</h3><strong>{s.since??'Not available'}</strong><p>{s.latest?`Adjustment: ${date(s.latest)}`:'No price adjustment recorded'}{s.since===null&&s.latest?' · Outside report coverage':''}</p></article><article><h3>Upcoming appointments</h3><strong>{s.upcoming.length?s.upcoming.length:'None listed'}</strong><p>Scheduled dates today or later in this report</p></article></div><p className="showing-note">ShowingTime report: {date(report.from)}–{date(report.through)}. Canceled appointments are excluded. Updates appear when a new report is imported; this is not a live schedule.</p>{s.upcoming.length>0&&<ul className="upcoming-list">{s.upcoming.map(a=><li key={a.date+a.start+a.end}><strong>{date(a.date)}</strong><span>{time(a.start)}–{time(a.end)} Eastern</span></li>)}</ul>}</>}</section>;
}
export function ShowingImport({report,onChange}){
 const [preview,setPreview]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function read(file){setPreview(null);setError('');if(!file)return;if(file.size>15*1024*1024){setError('Choose a PDF smaller than 15 MB.');return;}setBusy(true);let document,loadingTask;
 try{const pdfjs=await import('pdfjs-dist/build/pdf.mjs');const worker=await import('pdfjs-dist/build/pdf.worker.min.mjs?url');pdfjs.GlobalWorkerOptions.workerSrc=worker.default;loadingTask=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false});document=await loadingTask.promise;if(document.numPages>60)throw Error('Choose a report with no more than 60 pages.');let text='';for(let i=1;i<=document.numPages;i++){const page=await document.getPage(i);const content=await page.getTextContent();text+=content.items.map(item=>item.str||'').join(' ')+'\n';}setPreview(parseShowingReport(text));}catch(e){setError(e.message||'Unable to read this PDF.');}finally{try{if(loadingTask)await loadingTask.destroy();}finally{setBusy(false);}}}
 return <section className="editor"><h2>ShowingTime Report</h2><p className="muted">Upload the emailed Listing Activity Report PDF. Review the results, use the report, then save changes. Only appointment dates, times, status and report coverage are saved; the PDF, contact details and feedback stay out of the dashboard.</p>{report&&<p className="muted">Current report: {date(report.from)}–{date(report.through)}</p>}<label>Activity report PDF<input type="file" accept="application/pdf,.pdf" disabled={busy} onChange={e=>{read(e.target.files?.[0]);e.target.value='';}}/></label>{busy&&<p role="status">Reading appointment details…</p>}{error&&<p role="alert" className="error">{error}</p>}{preview&&<div className="import-preview"><h3>Review import</h3><p>{date(preview.from)}–{date(preview.through)}</p><p>{preview.appointments.filter(a=>a.status==='Completed').length} completed · {preview.appointments.filter(a=>a.status==='Scheduled').length} scheduled · {preview.appointments.filter(a=>a.status==='Requested').length} requested · {preview.appointments.filter(a=>a.status==='Canceled').length} canceled (excluded from counts)</p>{report&&preview.through<report.through?<p className="error">This report is older than the saved report. Upload a newer report.</p>:<><p className="muted">This replaces the previous showing report. Property status, pricing and strategy checkpoints are preserved.</p><button type="button" onClick={()=>{onChange(preview);setPreview(null);}}>Use this report</button></>}<button type="button" className="quiet" onClick={()=>setPreview(null)}>Cancel import</button></div>}{report&&<button type="button" className="danger" onClick={()=>{if(confirm('Remove the showing report? This takes effect when you save changes.'))onChange(null);}}>Remove report</button>}</section>;
}
